### ISSUE TITLE
[Notifications] Bot does not send a message if a notification is a substring of another existing notification

### ISSUE THREAD

**Issue by melonbreadjin** [drklee3/sushii-bot#4]
**Steps to reproduce:**

1. Add 3 notifications where the next notification is a substring of the previous one.
```
-notification add mmmtest
-notification add mmmt
-notification add mmm
```
2. Use a different user and type in `mmmt`

**Expected Behavior:**

sushii-bot notifies the user that someone mentioned the keyword `mmmt`.

**Observed Behavior:**

sushii-bot does not notify the user.

---

Tested on the lucky sushii server

**Comment by drklee3** [comment]
Thanks, the fix should be in place now.
