### ISSUE TITLE
[Reminder] Sushii bot does not properly parse reminders that contain the word `to` multiple times

### ISSUE THREAD

**Issue by melonbreadjin** [drklee3/sushii-bot#5]
**Steps to reproduce:**

1. Type `-remind me in 15 seconds to learn how to eat sushi`

**Expected Behavior:**

Sushii bot replies with `I'll remind you in 15 seconds (2018-09-03 12:26:37 UTC) to learn how to eat sushi`

**Observed Behavior:**

Sushii bot replies with `I'll remind you in 15 seconds (2018-09-03 12:26:37 UTC) to eat sushi`

**Possible Root Cause:**

`std::string::String.rfind()` at `src/commands/misc.rs line 129` returns the index of the second `to` and not the first occurrence

---

Tested on the lucky sushii server

**Comment by drklee3** [comment]
Thanks for the bug reports, this one should be fixed now as well.
