### ISSUE TITLE
[Reminder] Regex for days/hours/minutes/seconds are incomplete

### ISSUE THREAD

**Issue by melonbreadjin** [drklee3/sushii-bot#6]
**Steps to reproduce:**

1. Type `-remind me in 2 dogs 1 mule 15 sushi to sleep`

**Expected Behavior:**

Sushii bot throws an error.

**Observed Behavior:**

Sushii bot replies with `I'll remind you in 2 days, 1 minute and 15 seconds (2018-09-07 01:46:08 UTC) to sleep`

**Root Cause:**

Regex at `src/commands/misc.rs lines 76, 87, 101, 115` only checks for the first letter of the word.

---

Tested on the lucky sushii server

**Comment by drklee3** [comment]
RegEx should be adjusted now via https://github.com/drklee3/sushii-bot/commit/8ae67d03b90a57f8d3707509c30e424ff82e9b8b. Thanks!

It still allows for some weird combinations after the first part of the match, but IMO it should be fairly lenient on spelling after the first part (sec/min) to allow for typos or whatever.
