### ISSUE TITLE
[Reminder] Sushii bot allows reminders that are so far away from the future

### ISSUE THREAD

**Issue by melonbreadjin** [drklee3/sushii-bot#7]
**Steps to reproduce:**

1. Type `-remind me in 9999999 days to go to a resto`

**Observed Behavior:**

Sushii bot replies with `I'll remind you in 27397 years, 3 months and 4 days (+29397-09-27 12:41:31 UTC) to a resto`

**Notes:**

This could be used as a vector of attack to slow down the bot or overpopulate the database as these reminders won't expire and will be continually be checked. My suggestion is to either have a max number of reminders per user or a max duration for the reminder.

---

Tested on the lucky sushii server

**Comment by drklee3** [comment]
Reminders now limited to a max of 1 year ahead in the future via https://github.com/drklee3/sushii-bot/commit/13b0f7b6d399dadaeab3fcb39480500482b76531 and limited to max 200 per user via https://github.com/drklee3/sushii-bot/commit/edc979eb9c5f615b70e6249c4b3ba8b86b746676, can be adjusted if necessary later.  Thanks!
