### ISSUE TITLE
[Reminder] Sushii bot cannot retrieve time from when the reminder was set

### ISSUE THREAD

**Issue by melonbreadjin** [drklee3/sushii-bot#9]
**Steps to reproduce:**

1. Set a reminder `-remind me in 5s to test`

**Expected Behavior:**

Sushii bot sends you a DM 5 seconds later with the message:
```
Ding dong! The reminder you set 5 seconds ago has expired
test
```

**Observed Behavior:**

Sushii bot sends you a DM 5 seconds later with the message:
```
Ding dong! The reminder you set ??? has expired
test
```
***
Tested on the lucky sushii server

**Comment by melonbreadjin** [comment]
Possible root cause is the changes to `src/tasks/reminders.rs` on 6131c7a

**Comment by drklee3** [comment]
Thanks, didn't catch that when switching dependencies.  Should be fixed and in the running build now.
